### ISSUE TITLE
Register pott to pypi (version 0.10)

### ISSUE THREAD

**Issue by jun-harashima** [jun-harashima/pott#118]
# TODO
- [ ] write a document for global search (must)
- [ ] write a document for local search (must)
- [x] modify _search_other for local search (must) https://github.com/jun-harashima/pott/pull/120
- [ ] show cited_by (must)
- [ ] enable to update cited_by (optional)
